[project]
name = "3-spark-fundamentals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chispa>=0.10.1",
    "pyspark>=3.5.4",
    "pytest>=8.3.4",
    "pyspark[sql]>=3.5.4",
    "numpy>=1.26.4",
    "pip>=24.3.1",
]
